version: '3.4'

services:
  toshokan.applications.webapp:
    image: ${DOCKER_REGISTRY-}toshokanapplicationswebapp
    build:
      context: .
      dockerfile: Toshokan.Applications.Webapp/Dockerfile
    depends_on:
        - db

  #toshokan.functions.cleaner:
  #  image: ${DOCKER_REGISTRY-}toshokanfunctionscleaner
  #  build:
  #    context: .
  #    dockerfile: Toshokan.Functions.Cleaner/Dockerfile
  #  depends_on:
  #      - db


  #toshokan.functions.episodefetcher:
  #  image: ${DOCKER_REGISTRY-}toshokanfunctionsepisodefetcher
  #  build:
  #    context: .
  #    dockerfile: Toshokan.Functions.EpisodeFetcher/Dockerfile
  #  depends_on:
  #      - db

  #toshokan.functions.mangafetcher:
  #  image: ${DOCKER_REGISTRY-}toshokanfunctionsmangafetcher
  #  build:
  #    context: .
  #    dockerfile: Toshokan.Functions.MangaFetcher/Dockerfile
  #  depends_on:
  #      - db

  #toshokan.functions.pagefetcher:
  #  image: ${DOCKER_REGISTRY-}toshokanfunctionspagefetcher
  #  build:
  #    context: .
  #    dockerfile: Toshokan.Functions.PageFetcher/Dockerfile
  #  depends_on:
  #      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "P@ssword01"
      ACCEPT_EULA: "Y"